# Generated by Django 3.2.5 on 2021-12-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_type', models.CharField(max_length=100)),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('title_img', models.FileField(upload_to='')),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landseatechapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landseatechapp.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small', models.FileField(upload_to='')),
                ('big', models.FileField(upload_to='')),
                ('medium', models.FileField(upload_to='')),
                ('created_by', models.DateTimeField(auto_now=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landseatechapp.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
