# Generated by Django 3.2.5 on 2021-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0004_auto_20211214_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='big',
            field=models.FileField(blank=True, null=True, upload_to='images1/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.FileField(blank=True, null=True, upload_to='images2/'),
        ),
    ]
