# Generated by Django 3.2.5 on 2021-12-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0006_auto_20211215_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='created_by',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='updated_by',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_by',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='created_by',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_by',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_by',
            new_name='updated_on',
        ),
    ]
