# Generated by Django 3.2.5 on 2021-12-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0007_auto_20211215_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
