# Generated by Django 3.2.5 on 2021-12-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0008_auto_20211215_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
