# Generated by Django 3.2.5 on 2021-12-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0009_brand_brand_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_id',
            new_name='pdt_id',
        ),
    ]
