# Generated by Django 3.2.5 on 2021-12-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landseatechapp', '0012_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pdt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landseatechapp.product'),
        ),
    ]
